# Copyright (C) 2020  Sutou Kouhei <kou@clear-code.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

# cython: language_level = 3

cdef extern from "groonga.h":
    ctypedef enum grn_rc:
        SUCCESS "GRN_SUCCESS"
        END_OF_DATA "GRN_END_OF_DATA"
        UNKNOWN_ERROR "GRN_UNKNOWN_ERROR"
        OPERATION_NOT_PERMITTED "GRN_OPERATION_NOT_PERMITTED"
        NO_SUCH_FILE_OR_DIRECTORY "GRN_NO_SUCH_FILE_OR_DIRECTORY"
        NO_SUCH_PROCESS "GRN_NO_SUCH_PROCESS"
        INTERRUPTED_FUNCTION_CALL "GRN_INTERRUPTED_FUNCTION_CALL"
        INPUT_OUTPUT_ERROR "GRN_INPUT_OUTPUT_ERROR"
        NO_SUCH_DEVICE_OR_ADDRESS "GRN_NO_SUCH_DEVICE_OR_ADDRESS"
        ARG_LIST_TOO_LONG "GRN_ARG_LIST_TOO_LONG"
        EXEC_FORMAT_ERROR "GRN_EXEC_FORMAT_ERROR"
        BAD_FILE_DESCRIPTOR "GRN_BAD_FILE_DESCRIPTOR"
        NO_CHILD_PROCESSES "GRN_NO_CHILD_PROCESSES"
        RESOURCE_TEMPORARILY_UNAVAILABLE "GRN_RESOURCE_TEMPORARILY_UNAVAILABLE"
        NOT_ENOUGH_SPACE "GRN_NOT_ENOUGH_SPACE"
        PERMISSION_DENIED "GRN_PERMISSION_DENIED"
        BAD_ADDRESS "GRN_BAD_ADDRESS"
        RESOURCE_BUSY "GRN_RESOURCE_BUSY"
        FILE_EXISTS "GRN_FILE_EXISTS"
        IMPROPER_LINK "GRN_IMPROPER_LINK"
        NO_SUCH_DEVICE "GRN_NO_SUCH_DEVICE"
        NOT_A_DIRECTORY "GRN_NOT_A_DIRECTORY"
        IS_A_DIRECTORY "GRN_IS_A_DIRECTORY"
        INVALID_ARGUMENT "GRN_INVALID_ARGUMENT"
        TOO_MANY_OPEN_FILES_IN_SYSTEM "GRN_TOO_MANY_OPEN_FILES_IN_SYSTEM"
        TOO_MANY_OPEN_FILES "GRN_TOO_MANY_OPEN_FILES"
        INAPPROPRIATE_IO_CONTROL_OPERATION "GRN_INAPPROPRIATE_I_O_CONTROL_OPERATION"
        FILE_TOO_LARGE "GRN_FILE_TOO_LARGE"
        NO_SPACE_LEFT_ON_DEVICE "GRN_NO_SPACE_LEFT_ON_DEVICE"
        INVALID_SEEK "GRN_INVALID_SEEK"
        READ_ONLY_FILE_SYSTEM "GRN_READ_ONLY_FILE_SYSTEM"
        TOO_MANY_LINKS "GRN_TOO_MANY_LINKS"
        BROKEN_PIPE "GRN_BROKEN_PIPE"
        DOMAIN_ERROR "GRN_DOMAIN_ERROR"
        RESULT_TOO_LARGE "GRN_RESULT_TOO_LARGE"
        RESOURCE_DEADLOCK_AVOIDED "GRN_RESOURCE_DEADLOCK_AVOIDED"
        NO_MEMORY_AVAILABLE "GRN_NO_MEMORY_AVAILABLE"
        FILENAME_TOO_LONG "GRN_FILENAME_TOO_LONG"
        NO_LOCKS_AVAILABLE "GRN_NO_LOCKS_AVAILABLE"
        FUNCTION_NOT_IMPLEMENTED "GRN_FUNCTION_NOT_IMPLEMENTED"
        DIRECTORY_NOT_EMPTY "GRN_DIRECTORY_NOT_EMPTY"
        ILLEGAL_BYTE_SEQUENCE "GRN_ILLEGAL_BYTE_SEQUENCE"
        SOCKET_NOT_INITIALIZED "GRN_SOCKET_NOT_INITIALIZED"
        OPERATION_WOULD_BLOCK "GRN_OPERATION_WOULD_BLOCK"
        ADDRESS_IS_NOT_AVAILABLE "GRN_ADDRESS_IS_NOT_AVAILABLE"
        NETWORK_IS_DOWN "GRN_NETWORK_IS_DOWN"
        NO_BUFFER "GRN_NO_BUFFER"
        SOCKET_IS_ALREADY_CONNECTED "GRN_SOCKET_IS_ALREADY_CONNECTED"
        SOCKET_IS_NOT_CONNECTED "GRN_SOCKET_IS_NOT_CONNECTED"
        SOCKET_IS_ALREADY_SHUTDOWNED "GRN_SOCKET_IS_ALREADY_SHUTDOWNED"
        OPERATION_TIMEOUT "GRN_OPERATION_TIMEOUT"
        CONNECTION_REFUSED "GRN_CONNECTION_REFUSED"
        RANGE_ERROR "GRN_RANGE_ERROR"
        TOKENIZER_ERROR "GRN_TOKENIZER_ERROR"
        FILE_CORRUPT "GRN_FILE_CORRUPT"
        INVALID_FORMAT "GRN_INVALID_FORMAT"
        OBJECT_CORRUPT "GRN_OBJECT_CORRUPT"
        TOO_MANY_SYMBOLIC_LINKS "GRN_TOO_MANY_SYMBOLIC_LINKS"
        NOT_SOCKET "GRN_NOT_SOCKET"
        OPERATION_NOT_SUPPORTED "GRN_OPERATION_NOT_SUPPORTED"
        ADDRESS_IS_IN_USE "GRN_ADDRESS_IS_IN_USE"
        ZLIB_ERROR "GRN_ZLIB_ERROR"
        LZ4_ERROR "GRN_LZ4_ERROR"
        STACK_OVER_FLOW "GRN_STACK_OVER_FLOW"
        SYNTAX_ERROR "GRN_SYNTAX_ERROR"
        RETRY_MAX "GRN_RETRY_MAX"
        INCOMPATIBLE_FILE_FORMAT "GRN_INCOMPATIBLE_FILE_FORMAT"
        UPDATE_NOT_ALLOWED "GRN_UPDATE_NOT_ALLOWED"
        TOO_SMALL_OFFSET "GRN_TOO_SMALL_OFFSET"
        TOO_LARGE_OFFSET "GRN_TOO_LARGE_OFFSET"
        TOO_SMALL_LIMIT "GRN_TOO_SMALL_LIMIT"
        CAS_ERROR "GRN_CAS_ERROR"
        UNSUPPORTED_COMMAND_VERSION "GRN_UNSUPPORTED_COMMAND_VERSION"
        NORMALIZER_ERROR "GRN_NORMALIZER_ERROR"
        TOKEN_FILTER_ERROR "GRN_TOKEN_FILTER_ERROR"
        COMMAND_ERROR "GRN_COMMAND_ERROR"
        PLUGIN_ERROR "GRN_PLUGIN_ERROR"
        SCORER_ERROR "GRN_SCORER_ERROR"
        CANCEL "GRN_CANCEL"
        WINDOW_FUNCTION_ERROR "GRN_WINDOW_FUNCTION_ERROR"
        ZSTD_ERROR "GRN_ZSTD_ERROR"
        CONNECTION_RESET "GRN_CONNECTION_RESET"
