# Copyright (C) 2020  Sutou Kouhei <kou@clear-code.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

# cython: language_level = 3

from grnpy.grn_error cimport grn_rc

SUCCESS = grn_rc.SUCCESS
END_OF_DATA = grn_rc.END_OF_DATA
UNKNOWN_ERROR = grn_rc.UNKNOWN_ERROR
OPERATION_NOT_PERMITTED = grn_rc.OPERATION_NOT_PERMITTED
NO_SUCH_FILE_OR_DIRECTORY = grn_rc.NO_SUCH_FILE_OR_DIRECTORY
NO_SUCH_PROCESS = grn_rc.NO_SUCH_PROCESS
INTERRUPTED_FUNCTION_CALL = grn_rc.INTERRUPTED_FUNCTION_CALL
INPUT_OUTPUT_ERROR = grn_rc.INPUT_OUTPUT_ERROR
NO_SUCH_DEVICE_OR_ADDRESS = grn_rc.NO_SUCH_DEVICE_OR_ADDRESS
ARG_LIST_TOO_LONG = grn_rc.ARG_LIST_TOO_LONG
EXEC_FORMAT_ERROR = grn_rc.EXEC_FORMAT_ERROR
BAD_FILE_DESCRIPTOR = grn_rc.BAD_FILE_DESCRIPTOR
NO_CHILD_PROCESSES = grn_rc.NO_CHILD_PROCESSES
RESOURCE_TEMPORARILY_UNAVAILABLE = grn_rc.RESOURCE_TEMPORARILY_UNAVAILABLE
NOT_ENOUGH_SPACE = grn_rc.NOT_ENOUGH_SPACE
PERMISSION_DENIED = grn_rc.PERMISSION_DENIED
BAD_ADDRESS = grn_rc.BAD_ADDRESS
RESOURCE_BUSY = grn_rc.RESOURCE_BUSY
FILE_EXISTS = grn_rc.FILE_EXISTS
IMPROPER_LINK = grn_rc.IMPROPER_LINK
NO_SUCH_DEVICE = grn_rc.NO_SUCH_DEVICE
NOT_A_DIRECTORY = grn_rc.NOT_A_DIRECTORY
IS_A_DIRECTORY = grn_rc.IS_A_DIRECTORY
INVALID_ARGUMENT = grn_rc.INVALID_ARGUMENT
TOO_MANY_OPEN_FILES_IN_SYSTEM = grn_rc.TOO_MANY_OPEN_FILES_IN_SYSTEM
TOO_MANY_OPEN_FILES = grn_rc.TOO_MANY_OPEN_FILES
INAPPROPRIATE_IO_CONTROL_OPERATION = grn_rc.INAPPROPRIATE_IO_CONTROL_OPERATION
FILE_TOO_LARGE = grn_rc.FILE_TOO_LARGE
NO_SPACE_LEFT_ON_DEVICE = grn_rc.NO_SPACE_LEFT_ON_DEVICE
INVALID_SEEK = grn_rc.INVALID_SEEK
READ_ONLY_FILE_SYSTEM = grn_rc.READ_ONLY_FILE_SYSTEM
TOO_MANY_LINKS = grn_rc.TOO_MANY_LINKS
BROKEN_PIPE = grn_rc.BROKEN_PIPE
DOMAIN_ERROR = grn_rc.DOMAIN_ERROR
RESULT_TOO_LARGE = grn_rc.RESULT_TOO_LARGE
RESOURCE_DEADLOCK_AVOIDED = grn_rc.RESOURCE_DEADLOCK_AVOIDED
NO_MEMORY_AVAILABLE = grn_rc.NO_MEMORY_AVAILABLE
FILENAME_TOO_LONG = grn_rc.FILENAME_TOO_LONG
NO_LOCKS_AVAILABLE = grn_rc.NO_LOCKS_AVAILABLE
FUNCTION_NOT_IMPLEMENTED = grn_rc.FUNCTION_NOT_IMPLEMENTED
DIRECTORY_NOT_EMPTY = grn_rc.DIRECTORY_NOT_EMPTY
ILLEGAL_BYTE_SEQUENCE = grn_rc.ILLEGAL_BYTE_SEQUENCE
SOCKET_NOT_INITIALIZED = grn_rc.SOCKET_NOT_INITIALIZED
OPERATION_WOULD_BLOCK = grn_rc.OPERATION_WOULD_BLOCK
ADDRESS_IS_NOT_AVAILABLE = grn_rc.ADDRESS_IS_NOT_AVAILABLE
NETWORK_IS_DOWN = grn_rc.NETWORK_IS_DOWN
NO_BUFFER = grn_rc.NO_BUFFER
SOCKET_IS_ALREADY_CONNECTED = grn_rc.SOCKET_IS_ALREADY_CONNECTED
SOCKET_IS_NOT_CONNECTED = grn_rc.SOCKET_IS_NOT_CONNECTED
SOCKET_IS_ALREADY_SHUTDOWNED = grn_rc.SOCKET_IS_ALREADY_SHUTDOWNED
OPERATION_TIMEOUT = grn_rc.OPERATION_TIMEOUT
CONNECTION_REFUSED = grn_rc.CONNECTION_REFUSED
RANGE_ERROR = grn_rc.RANGE_ERROR
TOKENIZER_ERROR = grn_rc.TOKENIZER_ERROR
FILE_CORRUPT = grn_rc.FILE_CORRUPT
INVALID_FORMAT = grn_rc.INVALID_FORMAT
OBJECT_CORRUPT = grn_rc.OBJECT_CORRUPT
TOO_MANY_SYMBOLIC_LINKS = grn_rc.TOO_MANY_SYMBOLIC_LINKS
NOT_SOCKET = grn_rc.NOT_SOCKET
OPERATION_NOT_SUPPORTED = grn_rc.OPERATION_NOT_SUPPORTED
ADDRESS_IS_IN_USE = grn_rc.ADDRESS_IS_IN_USE
ZLIB_ERROR = grn_rc.ZLIB_ERROR
LZ4_ERROR = grn_rc.LZ4_ERROR
STACK_OVER_FLOW = grn_rc.STACK_OVER_FLOW
SYNTAX_ERROR = grn_rc.SYNTAX_ERROR
RETRY_MAX = grn_rc.RETRY_MAX
INCOMPATIBLE_FILE_FORMAT = grn_rc.INCOMPATIBLE_FILE_FORMAT
UPDATE_NOT_ALLOWED = grn_rc.UPDATE_NOT_ALLOWED
TOO_SMALL_OFFSET = grn_rc.TOO_SMALL_OFFSET
TOO_LARGE_OFFSET = grn_rc.TOO_LARGE_OFFSET
TOO_SMALL_LIMIT = grn_rc.TOO_SMALL_LIMIT
CAS_ERROR = grn_rc.CAS_ERROR
UNSUPPORTED_COMMAND_VERSION = grn_rc.UNSUPPORTED_COMMAND_VERSION
NORMALIZER_ERROR = grn_rc.NORMALIZER_ERROR
TOKEN_FILTER_ERROR = grn_rc.TOKEN_FILTER_ERROR
COMMAND_ERROR = grn_rc.COMMAND_ERROR
PLUGIN_ERROR = grn_rc.PLUGIN_ERROR
SCORER_ERROR = grn_rc.SCORER_ERROR
CANCEL = grn_rc.CANCEL
WINDOW_FUNCTION_ERROR = grn_rc.WINDOW_FUNCTION_ERROR
ZSTD_ERROR = grn_rc.ZSTD_ERROR
CONNECTION_RESET = grn_rc.CONNECTION_RESET
