# Copyright (C) 2020-2023  Sutou Kouhei <kou@clear-code.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: "Python ${{ matrix.python-version }}: ${{ matrix.runs-on }}"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        runs-on:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Groonga
        if: |
          matrix.runs-on == 'ubuntu-latest'
        run: |
          sudo -H add-apt-repository -y ppa:groonga/ppa
          sudo -H apt update
          sudo -H apt install -y -V --no-install-recommends \
            libgroonga-dev \
            pkg-config
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_build.txt
          pip install -r requirements_test.txt
      - name: Install
        run: |
          python3 setup.py install
      - name: Test
        run: |
          pytest testing
